### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by chraibi** [kanakmi/Deforgify#1]
I'm not sure what is it, so my description  of the issue is poor. 
But here is the screenshot and I hope it helps! :-)

<img width="703" alt="Screen Shot 2022-03-09 at 12 28 02" src="https://user-images.githubusercontent.com/5772973/157433108-d01bb118-48b0-452e-be7f-8a8aa66d2f2d.png">

**Comment by kanakmi** [comment]
Hey @chraibi 

Thank you so much for reporting this error. Due to time constraints in the hackathon, I did not fully test all the features of the app and realized all the PNG files were resulting in this error because I missed one important step before passing the image to the model. 

It has been fixed now. Do try again and reply to this message if it still doesn't work.

Thanks,
Kanak

**Comment by chraibi** [comment]
works!
